import os
import json
import re
import google.generativeai as genai
from fastapi import FastAPI, UploadFile, File
from dotenv import load_dotenv

load_dotenv()
genai.configure(api_key=os.getenv("GEMINI_API_KEY"))

model = genai.GenerativeModel("gemini-2.5-flash")

app = FastAPI()

@app.post("/generate-quiz")
async def generate_quiz(context_text: str):
    prompt = f"""
You are a technical interviewer.

Based on the following text:
{context_text}

Generate exactly 5 technical MCQ questions.

STRICT RULES:
- Return ONLY valid JSON
- No markdown
- No triple backticks
- No explanation

Format:
[
  {{
    "question": "string",
    "options": ["A", "B", "C", "D"],
    "answer": 0
  }}
]
"""

    response = model.generate_content(prompt)

    raw_text = response.text.strip()

    # Safety cleanup (in case Gemini still adds markdown)
    clean_text = re.sub(r"```json|```", "", raw_text).strip()

    try:
        quiz_json = json.loads(clean_text)
    except json.JSONDecodeError:
        return {
            "error": "Invalid JSON generated by model",
            "raw_output": raw_text
        }

    return {"quiz": quiz_json}
